export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const LIKE = 'LIKE';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const CREATECOMMENT = 'CREATECOMMENT';
export const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS';
export const CREATEQUESTION = 'CREATEQUESTION';
export const FETCH_ALL_QUESTIONS = 'FETCH_ALL_QUESTIONS';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const FETCH_ALL_NOTIFICATIONS = 'FETCH_ALL_NOTIFICATIONS';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';



